apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend-deployment
spec:
  selector:
    matchLabels:
      app: express
      tier: backend
  replicas: 2
  # refers to the pod
  template:
    metadata:
      labels:
        app: express
        tier: backend
    spec:
      containers:
        - name: express
          image: techstarteranhkim/express:latest
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 5050
