version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    ports:
      - "3000:80"
